---
title: "MKTG 212 - A5"
author: "Juan"
date: "March 16, 2017"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
library(knitr); library(leaps); library(ggplot2); library(dplyr); library(glmnet); library(ineq) ; library(corrplot); library('splines'); library("randomForest"); library("chron");library(tree); library(pROC); library(MASS); library(car); library("ResourceSelection"); library("gridExtra"); library("bestglm"); library("logisticPCA"); library("rARPACK"); library("psych"); library("nFactors");library(e1071); library("sampling"); library("data.table"); library("nnet");library("neuralnet");library("dismo");library("rpart"); library("ROCR"); library(readxl); library('latex2exp'); library(WriteXLS); library(gridExtra); library("stats")
knitr::opts_chunk$set(tidy=TRUE, fig.width=6,  fig.height=5, fig.align='left', dev = 'pdf')
opts_knit$set(root.dir = "/Users/Juan//Dropbox/000SeniorSpring/STAT 471/Data")
```

# Part 1

```{r}
library(readxl)
a5_data <- a5_demo
a5 <- a5_data

a5$`Respondent Number` <-  a5$`Respondent Number` %>% as.factor
a5$`Preference Group` <-  a5$`Preference Group` %>% as.factor
a5$Gender <-  a5$Gender  %>% as.factor
a5$`Marital Status` <-  a5$`Marital Status`  %>% as.factor
a5$`1st Time Purchase` <- a5$`1st Time Purchase`   %>% as.factor
a5$`Age Category` <-  a5$`Age Category`  %>% as.factor
a5$`Children Category` <- a5$`Children Category`   %>% as.factor
a5$`Income Category` <- a5$`Income Category`   %>% as.factor


KAchoosers <- which(a5$`Preference Group` == (a5$`Preference Group`  %>% unique %>% sort)[1]) %>% sort
middle <- which(a5$`Preference Group` == (a5$`Preference Group`  %>% unique %>% sort)[3]) %>% sort
KAnonchoosers <- which(a5$`Preference Group` == (a5$`Preference Group`  %>% unique %>% sort)[2]) %>% sort
nonmiddle <- c(KAchoosers, KAnonchoosers) %>% sort 

a5.nonmiddle = a5[nonmiddle,]

a5.nonmiddle %>% colnames
############################################################################################################
# Just 1,2
a5.nonmiddle$original <- a5.nonmiddle$`Preference Group` 
a5.nonmiddle$original  <- a5.nonmiddle$original  %>% as.numeric
a5.nonmiddle.knn <- kmeans(a5.nonmiddle[,3:10],2, nstart = 20)
a5.nonmiddle$knn2 <- a5.nonmiddle.knn$cluster
a5.nonmiddle[which(a5.nonmiddle$knn2  == 2),74] <- rep(3, (which(a5.nonmiddle$knn2  == 2) %>% len))
sum(a5.nonmiddle$knn2 == a5.nonmiddle$original)/nrow(a5.nonmiddle)
a5.nonmiddle.knn
#  1,3 versus 2
a5$original <- a5$`Preference Group` 
a5$original  <- a5$original  %>% as.numeric
a5[nonmiddle,73] <- rep(0, nrow(a5[nonmiddle,73]))
a5.knn <- kmeans(a5[,3:10],2, nstart = 20)
a5$knn123 <- a5.knn$cluster
a5[which(a5$knn123  == 0),74] <- rep(1, (which(a5$knn123  == 0) %>% len))
sum(a5$knn123 == a5$original)/nrow(a5) # 0.132
############################################################################################################

a5[KAchoosers,c(3:10)]    %>% unlist %>% as.numeric
a5[middle,c(3:10)] %>%  unlist %>% as.numeric
a5[KAnonchoosers,c(3:10)] %>% unlist %>% as.numeric

a5[KAchoosers,c(3:10)] %>% summary
a5[middle,c(3:10)] %>% summary
a5[KAnonchoosers,c(3:10)] %>% summary

n_distinct(a5[KAchoosers,c(4)])

n_distinct(a5[KAchoosers,c(4)]    %>% unlist %>% as.numeric)
           
           
           
(a5[KAchoosers,c(4)]    %>% unlist %>% as.numeric) %>% hist(breaks=35 , col="red",xlim=c(18,65), ylim=c(0,15), main="Age by Preference Group")
(a5[middle,c(4)]    %>% unlist %>% as.numeric) %>%hist(breaks=35,  col="purple",xlim=c(18,65), ylim=c(0,15), main="Age by Preference Group", add=TRUE)
(a5[KAnonchoosers,c(4)]    %>% unlist %>% as.numeric) %>%hist(breaks=35 , col="blue",xlim=c(18,65), ylim=c(0,15), main="Age by Preference Group",add=TRUE)

?hist



?kmeans

a5.nonmiddle.knn$cluster

survey$k <- as.factor(survey.knn$cluster)
survey.knn



```

```{r}
(a5[KAchoosers,c(3)]    %>% unlist %>% as.numeric) %>% hist(breaks=35 , col="red",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram")
(a5[middle,c(3)]    %>% unlist %>% as.numeric) %>%hist(breaks=35,  col="purple",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram", add=FALSE)
(a5[KAnonchoosers,c(3)]    %>% unlist %>% as.numeric) %>%hist(breaks=35 , col="blue",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram",add=FALSE)


```

```{r}
(a5[KAchoosers,c(5)]    %>% unlist %>% as.numeric) %>% hist(breaks=35 , col="red",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram")
(a5[middle,c(5)]    %>% unlist %>% as.numeric) %>%hist(breaks=35,  col="purple",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram", add=FALSE)
(a5[KAnonchoosers,c(5)]    %>% unlist %>% as.numeric) %>%hist(breaks=35 , col="blue",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram",add=FALSE)


```

```{r}
(a5[KAchoosers,c(6)]    %>% unlist %>% as.numeric) %>% hist(breaks=35 , col="red",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram")
(a5[middle,c(6)]    %>% unlist %>% as.numeric) %>%hist(breaks=35,  col="purple",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram", add=FALSE)
(a5[KAnonchoosers,c(6)]    %>% unlist %>% as.numeric) %>%hist(breaks=35 , col="blue",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram",add=FALSE)


```

```{r}
(a5[KAchoosers,c(7)]    %>% unlist %>% as.numeric) %>% hist(breaks=35 , col="red",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram")
(a5[middle,c(7)]    %>% unlist %>% as.numeric) %>%hist(breaks=35,  col="purple",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram", add=FALSE)
(a5[KAnonchoosers,c(7)]    %>% unlist %>% as.numeric) %>%hist(breaks=35 , col="blue",xlim=c(0,3), ylim=c(0,60), main="Overlapping Histogram",add=FALSE)


```


```{r}
a5[KAchoosers,c(3:10)] %>% summary
```


```{r}
a5[middle,c(3:10)] %>% summary
```

```{r}
a5[KAnonchoosers,c(3:10)] %>% summary
```

```{r }
views <- read.table("TV_viewing.txt", stringsAsFactors = FALSE, header = TRUE)
len <- function(i){length(i)}
```


```{r}
views$HHNumber <- views$HHNumber %>% as.factor
views %>% str
```

```{r}
views.NAcounts <- function(i){ sum(is.na(views[,i])) }
views.NApercol <- unlist(lapply(c(1:length(names(views))),views.NAcounts))
views.NApercol # Data has no NAs

views %>% names
```



